version: "3"

services:
  todo-app-prod:
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - 5200:5000
    env_file:
      - ./.env
  todo-app-dev:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - 5100:5000
    env_file: 
      - ./.env
    volumes:
      - type: bind
        source: ./todoapp
        target: /app/todoapp

  todo-app-tests:
    build:
      target: runtests
      context: .
      dockerfile: Dockerfile
    ports:
      - 5300:5000
    env_file:
      - ./.env.test
    